model_reviews/urls.py
"""urls module."""
from django.urls import path

from model_reviews.views import BulkReviewsView, ReviewView

app_name = "partners"

urlpatterns = [
    path("review/<int:pk>", ReviewView.as_view(), name="perform_review"),
    path("bulk-review", BulkReviewsView.as_view(), name="perform_bulk_review"),
]

model_reviews/models.py
"""Models module for model reviews."""

from typing import List, Optional

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.postgres.fields import JSONField
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from django.utils.module_loading import import_string
from django.utils.translation import gettext_lazy as _

from model_reviews.constants import (
    EMAIL_TEMPLATE,
    EMAIL_TEMPLATE_PATH,
    REVIEW_COMPLETE_EMAIL_SUBJ,
    REVIEW_COMPLETE_EMAIL_TXT,
    REVIEW_REQUEST_EMAIL_SUBJ,
    REVIEW_REQUEST_EMAIL_TXT,
    SANDBOX_FIELD,
)

USER = settings.AUTH_USER_MODEL


class BaseReview(models.Model):
    """Model definition for BaseReview."""

    APPROVED = "1"
    REJECTED = "2"
    PENDING = "3"

    STATUS_CHOICES = (
        (APPROVED, _("Approved")),
        (PENDING, _("Pending")),
        (REJECTED, _("Rejected")),
    )

    review_status = models.CharField(
        _("Review Status"),
        max_length=1,
        choices=STATUS_CHOICES,
        default=PENDING,
        blank=True,
        db_index=True,
    )
    review_date = models.DateTimeField(
        _("Review Date"), blank=True, default=None, null=True
    )

    class Meta:
        """Meta definition for BaseReview."""

        abstract = True


class AbstractReview(BaseReview):
    """Model definition for AbstractReview."""

    # model_review options
    # List of fields that need moderation/review
    monitored_fields: List[str] = ["review_status", "review_date"]
    # path to function that will be run after successful review
    side_effect_function: Optional[str] = None
    # path to function that will be used to determine reviewers
    set_reviewers_function: Optional[str] = None
    # path to function that will be used to determine the user for a review object
    set_user_function: Optional[str] = "model_reviews.side_effects.set_review_user"
    # path to function that will be used to send email to reviewers
    request_for_review_function: Optional[
        str
    ] = "model_reviews.emails.send_single_request_for_review"
    # path to function that will be used to send email to user after review
    review_complete_notify_function: Optional[
        str
    ] = "model_reviews.emails.send_review_complete_notice"
    # path to function that will be used to determine reviewers
    get_next_reviewers_function: Optional[str] = None
    # emails options
    review_request_email_subject = _(REVIEW_REQUEST_EMAIL_SUBJ)
    review_request_email_body = _(REVIEW_REQUEST_EMAIL_TXT)
    review_complete_email_subject = _(REVIEW_COMPLETE_EMAIL_SUBJ)
    review_complete_email_body = _(REVIEW_COMPLETE_EMAIL_TXT)
    email_template = EMAIL_TEMPLATE
    email_template_path = EMAIL_TEMPLATE_PATH

    # model fields
    review_reason = models.TextField(_("Review Reason"), blank=True, default="")

    class Meta:
        """Meta definition for AbstractReview."""

        abstract = True

    def revert(self) -> bool:
        """
        Revert the instance to its last saved state.

        This method deletes unsaved changes on source model instance.

        Returns:
            `True` if revert was possible, `False` otherwise.
        """
        model = self._meta.model
        try:
            self.refresh_from_db()
            return True
        except model.DoesNotExist:
            return False

    def run_side_effect(self, review_obj: models.Model = None) -> None:
        """
        Run side effect function.

        This method runs the side effect function defined on the approvable model.
        The side effect is run once after an approval/rejection.
        """
        if self.side_effect_function:
            side_effect = import_string(self.side_effect_function)
            side_effect(review_obj=review_obj)


class ModelReview(BaseReview):
    """Model definition for ModelReview."""

    user = models.ForeignKey(
        USER,
        related_name="modelreview_user",
        verbose_name=_("User"),
        on_delete=models.CASCADE,
        null=True,
        default=None,
        blank=True,
        help_text=_("The user who submitted the request for review"),
    )
    content_type = models.ForeignKey(
        ContentType, verbose_name=_("Content Type"), on_delete=models.CASCADE
    )
    object_id = models.PositiveIntegerField(_("Object ID"), db_index=True)
    content_object = GenericForeignKey("content_type", "object_id")
    created = models.DateTimeField(_("Created"), auto_now_add=True)
    modified = models.DateTimeField(_("Modified"), auto_now=True)
    data = JSONField(_("Data"), encoder=DjangoJSONEncoder, default=dict, blank=False)
    reviewers = models.ManyToManyField(
        USER,
        related_name="modelreview_reviewers",
        verbose_name=_("Reviewer(s)"),
        through="Reviewer",
        through_fields=("review", "user"),
    )

    class Meta:
        """Meta definition for ModelReview."""

        abstract = False
        app_label = "model_reviews"
        verbose_name = _("Model Review")
        verbose_name_plural = _("Model Reviews")
        indexes = [models.Index(fields=["content_type", "object_id"])]

    def __str__(self):
        """Unicode representation of ModelReview."""
        return f"{self.content_object} review"

    def get_diff(self, source: models.Model = None) -> Optional[List[str]]:
        """
        Return the difference between the source data and the data in review model.

        Returns:
            A list of monitored field names that are different in the source.

        """
        source = source or self.content_object
        data = self.data.get(SANDBOX_FIELD, dict())

        source_data = {
            field: getattr(source, field) for field in self._get_monitored_fields()
        }

        return [key for key in data.keys() if data[key] != source_data[key]] or None

    def _get_monitored_fields(self, source: models.Model = None) -> List[str]:
        """Return the list of monitored field names."""
        source = source or self.content_object
        return source.monitored_fields

    def needs_review(self) -> bool:
        """Check if review is needed."""
        return self.review_status == ModelReview.PENDING

    def update_sandbox(self, source: models.Model = None, do_save: bool = True) -> None:
        """Update fields of the sandbox to reflect the state of the source."""
        source = source or self.content_object
        fields = self._get_monitored_fields(source=source)
        values = {key: getattr(source, key) for key in fields if hasattr(source, key)}
        if self.data.get(SANDBOX_FIELD):
            self.data[SANDBOX_FIELD].update(values)
        else:
            self.data[SANDBOX_FIELD] = values
        if do_save:
            self.save()

    def send_review_complete_notification(self):
        """Send notification that review is complete."""
        if self.user and not self.needs_review():
            source = self.content_object
            if source.review_complete_notify_function:
                notify_func = import_string(source.review_complete_notify_function)
                notify_func(review_obj=self)


class Reviewer(BaseReview):
    """Model definition for Reviewer."""

    user = models.ForeignKey(USER, verbose_name=_("User"), on_delete=models.CASCADE)
    review = models.ForeignKey(
        "ModelReview", verbose_name=_("Model Review"), on_delete=models.CASCADE
    )
    created = models.DateTimeField(_("Created"), auto_now_add=True)
    modified = models.DateTimeField(_("Modified"), auto_now=True)
    level = models.IntegerField(
        _("Level"),
        default=0,
        blank=True,
        db_index=True,
        help_text=_(
            "Used to control when a reviewer is asked for their review. "
            "For example, a level 2 reviewer may have to wait until all "
            "level 1 reviews are done."
        ),
    )
    reviewed = models.BooleanField(
        _("Reviewed"), default=False, blank=True, db_index=True
    )

    class Meta:
        """Meta definition for Reviewer."""

        app_label = "model_reviews"
        verbose_name = _("Reviewer")
        verbose_name_plural = _("Reviewers")
        unique_together = [["user", "review"]]

    def __str__(self):
        """Unicode representation of Reviewer."""
        return f"{self.user} review for {self.review}"

    def send_request_for_review(self):
        """Send a notification for request to perform review."""
        if self.review.content_object:
            if self.review.content_object.request_for_review_function:
                notify_func = import_string(
                    self.review.content_object.request_for_review_function
                )
                notify_func(self)

model_reviews/views.py
"""Views module for model reviews."""
from typing import List, Optional

from django.http import HttpResponseRedirect
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import DetailView, FormView
from django.views.generic.base import TemplateView
from django.views.generic.detail import SingleObjectMixin

from braces.views import FormInvalidMessageMixin, FormValidMessageMixin, MessageMixin

from model_reviews.constants import (
    REVIEW_FORM_FAIL_MSG,
    REVIEW_FORM_SUCCESS_MSG,
    REVIEW_FORMSET_FAIL_MSG,
    REVIEW_FORMSET_SUCCESS_MSG,
)
from model_reviews.forms import get_review_form
from model_reviews.formset import get_review_formset
from model_reviews.models import ModelReview


class ReviewFormMixin:  # pylint: disable=too-few-public-methods
    """Mixin that implements a method to get review form."""

    model = ModelReview
    template_name = "model_reviews/modelreview_detail.html"

    def get_form_class(self):
        """Return the form class to use."""
        return get_review_form(review=self.get_object(), user=self.request.user)


class ReviewDisplay(ReviewFormMixin, DetailView):
    """Detailview for a model review object."""

    def get_context_data(self, **kwargs):
        """Get context data."""
        context = super().get_context_data(**kwargs)
        form_class = self.get_form_class()
        context["form"] = form_class()
        return context


class ReviewForm(  # pylint: disable=bad-continuation
    FormInvalidMessageMixin,
    FormValidMessageMixin,
    ReviewFormMixin,
    SingleObjectMixin,
    FormView,
):
    """FormView for a review."""

    form_invalid_message = _(REVIEW_FORM_FAIL_MSG)
    form_valid_message = _(REVIEW_FORM_SUCCESS_MSG)

    def post(self, request, *args, **kwargs):
        """Set self.object."""
        self.object = (  # pylint: disable=attribute-defined-outside-init
            self.get_object()
        )
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        """Get the success url."""
        return "/"

    def form_valid(self, form):
        """If the form is valid, save the review."""
        form.save()
        return super().form_valid(form)


class ReviewView(View):
    """
    View used to display details of a ModelReview object.

    This view shows both the model review object details as well as handles the
    form to perform a review.

    The structure is inspired by:
        https://docs.djangoproject.com/en/3.0/topics/class-based-views/mixins/#an-alternative-better-solution
    """

    def get(self, request, *args, **kwargs):
        """Get the ReviewDisplay view."""
        view = ReviewDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """Get the ReviewForm view."""
        view = ReviewForm.as_view()
        return view(request, *args, **kwargs)


class BulkReviewsView(MessageMixin, TemplateView):
    """View used to handle bulk reviews."""

    initial: List[dict] = []
    success_url: Optional[str] = None
    prefix: Optional[str] = None
    template_name = "model_reviews/bulk.html"
    formset_invalid_message = _(REVIEW_FORMSET_FAIL_MSG)
    formset_valid_message = _(REVIEW_FORMSET_SUCCESS_MSG)

    def get_initial(self):
        """Return a copy of the initial data to use for formsets on this view."""
        return self.initial[:]

    def get_prefix(self):
        """Return the prefix to use for forms."""
        return self.prefix

    def get_formset_class(self):
        """Get formset."""
        return get_review_formset(user=self.request.user)

    def get_formset(self, formset_class=None):
        """Return an instance of the formset to be used in this view."""
        if formset_class is None:
            formset_class = self.get_formset_class()
        return formset_class(**self.get_formset_kwargs())

    def get_formset_kwargs(self):
        """Return the keyword arguments for instantiating the formset."""
        kwargs = {
            "initial": self.get_initial(),
            "prefix": self.get_prefix(),
        }

        if self.request.method in ("POST", "PUT"):
            kwargs.update(
                {
                    "data": self.request.POST,
                    "files": self.request.FILES,
                }  # flake8: noqa
            )
        return kwargs

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form."""
        if not self.success_url:
            return self.request.get_full_path()
        return str(self.success_url)  # success_url may be lazy

    def get_context_data(self, **kwargs):
        """Insert the formset into the context dict."""
        if "formset" not in kwargs:
            kwargs["formset"] = self.get_formset()
        return super().get_context_data(**kwargs)

    def formset_valid(self, formset):  # pylint: disable=unused-argument
        """If the form is valid, redirect to the supplied URL."""
        for form in formset:
            if form.has_changed():
                form.save()
        self.messages.success(self.formset_valid_message, fail_silently=True)
        return HttpResponseRedirect(self.get_success_url())

    def formset_invalid(self, formset):
        """If the form is invalid, render the invalid form."""
        self.messages.error(self.formset_invalid_message, fail_silently=True)
        return self.render_to_response(self.get_context_data(formset=formset))

    def post(self, request, *args, **kwargs):  # pylint: disable=unused-argument
        """
        Handle POST requests.

        Instantiate a form instance with the passed POST variables and then
        check if it's valid.
        """
        formset = self.get_formset()
        if formset.is_valid():
            return self.formset_valid(formset)
        return self.formset_invalid(formset)

    # PUT is a valid HTTP verb for creating (with a known URL) or editing an
    # object, note that browsers only support POST for now.
    def put(self, *args, **kwargs):
        """Handle PUT requests."""
        return self.post(*args, **kwargs)

model_reviews/templates/model_reviews/bulk.html
{% load i18n %}
<form method="post">
    {% csrf_token %}
    {% if formset.non_form_errors %}
    <ul class="non-form-errors">
        {% for error in formset.non_form_errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <table>
        {{ formset }}
    </table>
    {% if formset.total_form_count > 0 %}
        <div>
            <input type="submit" name="submit" />
        </div>
    {% else %}
        <p>{% trans "Nothing to see here." %}</p>
    {% endif %}
</form>

model_reviews/templates/model_reviews/modelreview_detail.html
{% load i18n %}
<!-- uncomment to use django.contrib.comments -->
{# {% load comments %} #}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% trans "Submit Review" %}</title>
    <meta name="description" content="Review Description">
    <meta name="author" content="Kelvin Jayanoris">
    <style>
        .grid {
            display: flex;
            flex-wrap: wrap;
        }

        .column {
            box-sizing: border-box;
            flex: 1;
        }

        .bigger {
            flex: 2.5;
        }

        .halves .column {
            flex: 0 0 50%;
        }

        .thirds .column {
            flex: 0 0 33.3333%;
        }

        .fourths .column {
            flex: 0 0 25%;
        }

        @media (max-width: 900px) {
            .grid {
                display: block;
            }
        }
    </style>
    <style>
        section {
            display: flex;
            flex-flow: row wrap;
        }

        section>div {
            flex: 1;
            padding: 0.5rem;
        }

        input[type="radio"] {
            display: none;
        }

        input[type="radio"]:not(:disabled)~label {
            cursor: pointer;
        }

        input[type="radio"]:disabled~label {
            color: #bcc2bf;
            border-color: #bcc2bf;
            box-shadow: none;
            cursor: not-allowed;
        }

        label {
            display: block;
            background: white;
            border-radius: 3%;
            padding: 0.7rem;
            margin-bottom: 0;
            text-align: center;
            position: relative;
            border: 1px solid #5562eb;
        }

        .btnbtn {
            display: block;
            width: 100%;
            background: #4CAF50;
            color: white;
            border-radius: 3%;
            padding: 1rem;
            margin-bottom: 0;
            text-align: center;
            position: relative;
            border: 1px solid #4CAF50;
            cursor: pointer;
            font-weight: 900;
        }

        .btnbtn.info {
            cursor: not-allowed;
        }

        .btnbtn.rejected {
            background: #ff0000;
        }

        hr {
            margin: 1rem 0;
        }

        .review_reason {
            background-color: aliceblue;
            padding: 0.5rem;
            margin-top: 0.5rem;
            border-radius: 5%;
        }

        .review_reason::after {
            content: "";
            position: absolute;
            top: -1.2rem;
            left: 2rem;
            border: 1rem solid transparent;
            border-bottom-color: aliceblue;
            display: block;
            width: 0;
        }

        .comment-item {
            background-color: #fbfbff;
            margin-bottom: 0.6rem;
        }

        .comment-header {
            margin-top: 0.2rem;
            margin-bottom: -0.5rem;
            font-size: 0.9rem;
            color: #828282;
        }

        .commentarea textarea {
            margin-top: 1rem;
        }

        .commentarea button {
            margin-top: 0.5rem;
        }

        .btn-comment {
            display: block;
            padding: 0.2rem;
            text-align: center;
            cursor: pointer;
        }

        textarea {
            width: 100%;
        }

        input[type="radio"]:checked+label {
            background: #5562eb;
            color: white;
        }

        input[type="radio"]#review-reject:checked+label {
            background: #ff0000;
            border-color: #ff0000;
        }

        @media only screen and (max-width: 700px) {
            section {
                flex-direction: column;
            }
        }

        .content-box {
            margin: 0 auto;
            max-width: 800px;
        }

        .non-field-errors,
        .hidden-field-errors,
        .status-field-errors {
            font-size: 0.9rem;
            color: #ff0000;
        }

        .status-field-errors div {
            padding: 0 0.5rem;
        }
    </style>
</head>

<body>
    <div class="content-box">
        <h1 style="text-align: center;">{% trans "Submit Review" %}</h1>
        <div class="grid">
            <div class="column">
                <p>Please submit a review for this item</p>
                <!--
                    This section is meant to output details on the item being
                    reviewed so that a review can make an informed decision.
                -->
            </div>
            <div class="column">
                <form method="POST" action="">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                        <ul class="non-field-errors">
                        {% for error in form.non_field_errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}

                    {% for hidden_field in form.hidden_fields %}
                        <ul class="hidden-field-errors">
                            {% if hidden_field.errors %}
                                {% for error in hidden_field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                        {{ hidden_field }}
                    {% endfor %}

                    {% if object.review_status == object.PENDING %}
                        <section id="id_review_status">
                            <div>
                                <input type="radio" id="review-approve" name="review_status" value="1">
                                <label for="review-approve">{% trans "Approve" %}</label>
                            </div>
                            <div>
                                <input type="radio" id="review-reject" name="review_status" value="2">
                                <label for="review-reject">{% trans "Reject" %}</label>
                            </div>
                        </section>
                        {% for error in form.review_status.errors %}
                            <section class="status-field-errors"><div>{{ error }}</div></section>
                        {% endfor %}
                        <section>
                            <div>
                                <button type="submit" class="btnbtn">{% trans "Submit Review" %}</button>
                            </div>
                        </section>
                    {% elif object.review_status == object.APPROVED %}
                        <section>
                            <div>
                                <button type="button" class="btnbtn info" disabled>{% trans "Approved" %}</button>
                            </div>
                        </section>
                    {% elif object.review_status == object.REJECTED %}
                        <section>
                            <div>
                                <button type="button" class="btnbtn info rejected" disabled>{% trans "Rejected" %}</button>
                            </div>
                        </section>
                    {% endif %}
                </form>
            </div>
        </div>
        {% if object.content_object.review_reason %}
        <div class="grid" style="position:relative;">
            <div class="column review_reason">
                {{ object.content_object.review_reason|linebreaks }}
            </div>
        </div>
        {% endif %}
        <!-- COMMENTS SECTION -->
        <!-- uncomment these to show comments list and form using django.contrib.comments -->
        <!-- <hr /> -->
        {# {% render_comment_list for object %} #}
        {# {% render_comment_form for object %} #}
        <!-- End of comments -->
        <!-- END COMMENTS SECTION -->
    </div>
</body>

</html>